FROM maxwinch/php:7.4-fpm
RUN apt-get install -y gnupg gnupg2 gnupg1 \
    && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl https://packages.microsoft.com/config/debian/11/prod.list > /etc/apt/sources.list.d/mssql-release.list \
    && apt-get update \
    && ACCEPT_EULA=Y apt-get install -y msodbcsql18 \
    # optional: for bcp and sqlcmd
    && ACCEPT_EULA=Y apt-get install -y mssql-tools18 \
    && echo 'export PATH="$PATH:/opt/mssql-tools18/bin"' >> ~/.bashrc \
    && /bin/bash -c 'source ~/.bashrc' \
    # optional: for unixODBC development headers
    && apt-get install -y unixodbc-dev \
    # optional: kerberos library for debian-slim distributions
    && apt-get install -y libgssapi-krb5-2 \
    && pecl install sqlsrv-5.10.1 pdo_sqlsrv-5.10.1 \
    && docker-php-ext-enable sqlsrv pdo_sqlsrv \
    # fanyi depend
    && docker-php-ext-configure gettext --with-gettext \
    && docker-php-ext-install gettext \
    && cd /var/www && php -r "readfile('https://getcomposer.org/installer');" | php \
    && mv /var/www/composer.phar /usr/local/bin/composer && chmod 755 /usr/local/bin/composer
